stages:
  - format
  - build

clang-format:
  stage: format
  image: suyuemu/cibuild:linux-x64
  variables:
    RELEASE_NAME: mainline
  script:
    - git submodule update --init --depth 1 --recursive
    - bash .ci/scripts/format/script.sh

build-linux:
  stage: build
  image: suyuemu/cibuild:linux-x64
  resource_group: linux-ci
  variables:
    RELEASE_NAME: mainline
  cache:
    paths:
      - ccache/
  before_script:
    - mkdir -p ccache
    - export CCACHE_BASEDIR=${PWD}
    - export CCACHE_DIR=${PWD}/ccache
  script:
    - git submodule update --init --depth 1 --recursive
    - bash .ci/scripts/linux/docker.sh
    - bash .ci/scripts/linux/upload.sh
  artifacts:
    paths:
      - artifacts/*
